services:
  redis:
    image: redis:7.4
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./redis_logs:/var/log/redis

  postgres:
    image: postgres:17.0
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_logs:/var/log/postgresql