# multiapp/charts/python-backend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: python-backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}