apiVersion: v1
kind: Service
metadata:
  name: node-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: node-backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http